// This file would typically be auto-generated by OpenAPI Generator
// representing the Backend DTOs.

export interface PatientDTO {
  id: string;
  firstName: string;
  lastName: string;
  dateOfBirth: string;
  gender: 'M' | 'F' | 'O';
  status: 'active' | 'discharged';
  riskScore: 'low' | 'medium' | 'high';
}

export interface DeploymentDTO {
    id: string;
    name: string;
    version: string;
    configuration: Record<string, any>;
    status: 'draft' | 'published' | 'archived';
}

export interface TelemetryEvent {
    deviceId: string;
    patientId: string;
    timestamp: string;
    type: 'spo2' | 'hr' | 'bp' | 'weight';
    value: number;
    unit: string;
}
